// @generated by protoc-gen-es v2.5.2 with parameter "target=js+dts,import_extension=.js"
// @generated from file auth/get_auth_token.proto (package stately.auth, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file auth/get_auth_token.proto.
 */
export const file_auth_get_auth_token =
  /*@__PURE__*/
  fileDesc(
    "ChlhdXRoL2dldF9hdXRoX3Rva2VuLnByb3RvEgxzdGF0ZWx5LmF1dGgiNwoTR2V0QXV0aFRva2VuUmVxdWVzdBIUCgphY2Nlc3Nfa2V5GAEgASgJSABCCgoIaWRlbnRpdHkiQAoUR2V0QXV0aFRva2VuUmVzcG9uc2USEgoKYXV0aF90b2tlbhgBIAEoCRIUCgxleHBpcmVzX2luX3MYAiABKARCdgoQY29tLnN0YXRlbHkuYXV0aEIRR2V0QXV0aFRva2VuUHJvdG9QAaICA1NBWKoCDFN0YXRlbHkuQXV0aMoCDFN0YXRlbHlcQXV0aOICGFN0YXRlbHlcQXV0aFxHUEJNZXRhZGF0YeoCDVN0YXRlbHk6OkF1dGhiBnByb3RvMw",
  );

/**
 * Describes the message stately.auth.GetAuthTokenRequest.
 * Use `create(GetAuthTokenRequestSchema)` to create a new message.
 */
export const GetAuthTokenRequestSchema = /*@__PURE__*/ messageDesc(file_auth_get_auth_token, 0);

/**
 * Describes the message stately.auth.GetAuthTokenResponse.
 * Use `create(GetAuthTokenResponseSchema)` to create a new message.
 */
export const GetAuthTokenResponseSchema = /*@__PURE__*/ messageDesc(file_auth_get_auth_token, 1);
