// @generated by protoc-gen-es v2.3.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file auth/get_auth_token.proto (package stately.auth, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file auth/get_auth_token.proto.
 */
export declare const file_auth_get_auth_token: GenFile;

/**
 * @generated from message stately.auth.GetAuthTokenRequest
 */
export declare type GetAuthTokenRequest = Message<"stately.auth.GetAuthTokenRequest"> & {
  /**
   * @generated from oneof stately.auth.GetAuthTokenRequest.identity
   */
  identity:
    | {
        /**
         * access_key is an access key that has been added to an organization via
         * stately.user.UserService.CreateAccessKey. It is a sensitive secret used
         * for programmatic access to Stately APIs, equivalent to a
         * username+password.
         *
         * @generated from field: string access_key = 1;
         */
        value: string;
        case: "accessKey";
      }
    | { case: undefined; value?: undefined };
};

/**
 * Describes the message stately.auth.GetAuthTokenRequest.
 * Use `create(GetAuthTokenRequestSchema)` to create a new message.
 */
export declare const GetAuthTokenRequestSchema: GenMessage<GetAuthTokenRequest>;

/**
 * @generated from message stately.auth.GetAuthTokenResponse
 */
export declare type GetAuthTokenResponse = Message<"stately.auth.GetAuthTokenResponse"> & {
  /**
   * auth_token is the token that can be used to authenticate requests to the
   * StatelyDB API.
   *
   * @generated from field: string auth_token = 1;
   */
  authToken: string;

  /**
   * expires_in_s is the duration in seconds that this access token is
   * valid. After this time has passed, the access token will be rejected - you
   * should refresh the token via another call to GetAuthToken before this
   * happens.
   *
   * @generated from field: uint64 expires_in_s = 2;
   */
  expiresInS: bigint;
};

/**
 * Describes the message stately.auth.GetAuthTokenResponse.
 * Use `create(GetAuthTokenResponseSchema)` to create a new message.
 */
export declare const GetAuthTokenResponseSchema: GenMessage<GetAuthTokenResponse>;
