// @generated by protoc-gen-es v2.2.5 with parameter "target=js+dts,import_extension=.js"
// @generated from file auth/service.proto (package stately.auth, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { GetAuthTokenRequestSchema, GetAuthTokenResponseSchema } from "./get_auth_token_pb.js";

/**
 * Describes the file auth/service.proto.
 */
export declare const file_auth_service: GenFile;

/**
 * AuthService is the service for vending access tokens used to connect to
 * StatelyDB. This API is meant to be used from SDKs. Access Keys are created
 * and managed from the stately.dbmanagement.UserService.
 *
 * @generated from service stately.auth.AuthService
 */
export declare const AuthService: GenService<{
  /**
   * GetAuthToken returns a short-lived access token from some proof of
   * identity. This operation will fail if the identity cannot be verified.
   *
   * @generated from rpc stately.auth.AuthService.GetAuthToken
   */
  getAuthToken: {
    methodKind: "unary";
    input: typeof GetAuthTokenRequestSchema;
    output: typeof GetAuthTokenResponseSchema;
  };
}>;
