// @generated by protoc-gen-es v2.8.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file errors/error_details.proto (package stately.errors, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file errors/error_details.proto.
 */
export const file_errors_error_details =
  /*@__PURE__*/
  fileDesc(
    "ChplcnJvcnMvZXJyb3JfZGV0YWlscy5wcm90bxIOc3RhdGVseS5lcnJvcnMiYgoTU3RhdGVseUVycm9yRGV0YWlscxIUCgxzdGF0ZWx5X2NvZGUYASABKAkSDwoHbWVzc2FnZRgCIAEoCRIWCg51cHN0cmVhbV9jYXVzZRgDIAEoCRIMCgRjb2RlGAQgASgNQoABChJjb20uc3RhdGVseS5lcnJvcnNCEUVycm9yRGV0YWlsc1Byb3RvUAGiAgNTRViqAg5TdGF0ZWx5LkVycm9yc8oCDlN0YXRlbHlcRXJyb3Jz4gIaU3RhdGVseVxFcnJvcnNcR1BCTWV0YWRhdGHqAg9TdGF0ZWx5OjpFcnJvcnNiBnByb3RvMw",
  );

/**
 * Describes the message stately.errors.StatelyErrorDetails.
 * Use `create(StatelyErrorDetailsSchema)` to create a new message.
 */
export const StatelyErrorDetailsSchema = /*@__PURE__*/ messageDesc(file_errors_error_details, 0);
