// @generated by protoc-gen-es v2.5.2 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/continue_scan.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file db/continue_scan.proto.
 */
export const file_db_continue_scan =
  /*@__PURE__*/
  fileDesc(
    "ChZkYi9jb250aW51ZV9zY2FuLnByb3RvEgpzdGF0ZWx5LmRiIlcKE0NvbnRpbnVlU2NhblJlcXVlc3QSEgoKdG9rZW5fZGF0YRgBIAEoDBIZChFzY2hlbWFfdmVyc2lvbl9pZBgCIAEoDRIRCglzY2hlbWFfaWQYAyABKARCbAoOY29tLnN0YXRlbHkuZGJCEUNvbnRpbnVlU2NhblByb3RvUAGiAgNTRFiqAgpTdGF0ZWx5LkRiygIKU3RhdGVseVxEYuICFlN0YXRlbHlcRGJcR1BCTWV0YWRhdGHqAgtTdGF0ZWx5OjpEYmIGcHJvdG8z",
  );

/**
 * Describes the message stately.db.ContinueScanRequest.
 * Use `create(ContinueScanRequestSchema)` to create a new message.
 */
export const ContinueScanRequestSchema = /*@__PURE__*/ messageDesc(file_db_continue_scan, 0);
