// @generated by protoc-gen-es v2.2.3 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/continue_scan.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file db/continue_scan.proto.
 */
export const file_db_continue_scan =
  /*@__PURE__*/
  fileDesc(
    "ChZkYi9jb250aW51ZV9zY2FuLnByb3RvEgpzdGF0ZWx5LmRiIkQKE0NvbnRpbnVlU2NhblJlcXVlc3QSEgoKdG9rZW5fZGF0YRgBIAEoDBIZChFzY2hlbWFfdmVyc2lvbl9pZBgCIAEoDUJsCg5jb20uc3RhdGVseS5kYkIRQ29udGludWVTY2FuUHJvdG9QAaICA1NEWKoCClN0YXRlbHkuRGLKAgpTdGF0ZWx5XERi4gIWU3RhdGVseVxEYlxHUEJNZXRhZGF0YeoCC1N0YXRlbHk6OkRiYgZwcm90bzM",
  );

/**
 * Describes the message stately.db.ContinueScanRequest.
 * Use `create(ContinueScanRequestSchema)` to create a new message.
 */
export const ContinueScanRequestSchema = /*@__PURE__*/ messageDesc(file_db_continue_scan, 0);
