// @generated by protoc-gen-es v2.6.1 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/continue_scan.proto (package stately.db, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file db/continue_scan.proto.
 */
export declare const file_db_continue_scan: GenFile;

/**
 * @generated from message stately.db.ContinueScanRequest
 */
export declare type ContinueScanRequest = Message<"stately.db.ContinueScanRequest"> & {
  /**
   * token_data is an opaque list continuation token returned by a previous call
   * to BeginScan or ContinueScan.
   *
   * @generated from field: bytes token_data = 1;
   */
  tokenData: Uint8Array;

  /**
   * schema_version_id is the schema version id the client is using. This is
   * used to ensure the same schema version is used across each page of the list.
   * If the version the token was created with is different from the client's
   * current version, the operation will error with SchemaVersionMismatch error,
   * in which case you should start over with a fresh BeginScan call.
   *
   * @generated from field: uint32 schema_version_id = 2;
   */
  schemaVersionId: number;

  /**
   * schema_id refers to the schema to use for this operation.
   * If the store_id does not have a schema with this ID, the operation will
   * error with SchemaNotFound error. You should not have to set this manually
   * as your generated SDK should know its schema and wire this in for you.
   *
   * ; (after clients have been regen'd and updated)
   *
   * @generated from field: uint64 schema_id = 3;
   */
  schemaId: bigint;
};

/**
 * Describes the message stately.db.ContinueScanRequest.
 * Use `create(ContinueScanRequestSchema)` to create a new message.
 */
export declare const ContinueScanRequestSchema: GenMessage<ContinueScanRequest>;
