// @generated by protoc-gen-es v2.3.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/continue_list.proto (package stately.db, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file db/continue_list.proto.
 */
export declare const file_db_continue_list: GenFile;

/**
 * @generated from message stately.db.ContinueListRequest
 */
export declare type ContinueListRequest = Message<"stately.db.ContinueListRequest"> & {
  /**
   * token_data is an opaque list continuation token returned by a previous call to
   * BeginList, ContinueList, or SyncList.
   *
   * @generated from field: bytes token_data = 1;
   */
  tokenData: Uint8Array;

  /**
   * direction indicates whether we are expanding the result set (paginating)
   * forward (in the direction of the original List operation) or backward (in
   * the opposite direction). The default is to expand forward.
   *
   * @generated from field: stately.db.ContinueListDirection direction = 2;
   */
  direction: ContinueListDirection;

  /**
   * schema_version_id is the schema version id the client is using. This is
   * used to ensure the same schema version is used across each page of the list.
   * If the version the token was created with is different from the client's
   * current version, the operation will error with SchemaVersionMismatch error,
   * in which case you should start over with a fresh BeginList call.
   *
   * @generated from field: uint32 schema_version_id = 5;
   */
  schemaVersionId: number;

  /**
   * schema_id refers to the schema to use for this operation.
   * If the store_id does not have a schema with this ID, the operation will
   * error with SchemaNotFound error. You should not have to set this manually
   * as your generated SDK should know its schema and wire this in for you.
   *
   * ; (after clients have been regen'd and updated)
   *
   * @generated from field: uint64 schema_id = 6;
   */
  schemaId: bigint;
};

/**
 * Describes the message stately.db.ContinueListRequest.
 * Use `create(ContinueListRequestSchema)` to create a new message.
 */
export declare const ContinueListRequestSchema: GenMessage<ContinueListRequest>;

/**
 * ContinueListDirection is used to indicate whether we are expanding the result
 * set (paginating) forward (in the direction of the original List operation) or
 * backward (in the opposite direction).
 *
 * @generated from enum stately.db.ContinueListDirection
 */
export enum ContinueListDirection {
  /**
   * this is the default
   *
   * @generated from enum value: CONTINUE_LIST_FORWARD = 0;
   */
  CONTINUE_LIST_FORWARD = 0,

  /**
   * @generated from enum value: CONTINUE_LIST_BACKWARD = 1;
   */
  CONTINUE_LIST_BACKWARD = 1,
}

/**
 * Describes the enum stately.db.ContinueListDirection.
 */
export declare const ContinueListDirectionSchema: GenEnum<ContinueListDirection>;
