// @generated by protoc-gen-es v2.2.4 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/delete.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file db/delete.proto.
 */
export const file_db_delete =
  /*@__PURE__*/
  fileDesc(
    "Cg9kYi9kZWxldGUucHJvdG8SCnN0YXRlbHkuZGIifgoNRGVsZXRlUmVxdWVzdBIQCghzdG9yZV9pZBgBIAEoBBInCgdkZWxldGVzGAMgAygLMhYuc3RhdGVseS5kYi5EZWxldGVJdGVtEhkKEXNjaGVtYV92ZXJzaW9uX2lkGAUgASgNEhEKCXNjaGVtYV9pZBgGIAEoBEoECAQQBSIeCgpEZWxldGVJdGVtEhAKCGtleV9wYXRoGAEgASgJIiYKDERlbGV0ZVJlc3VsdBIQCghrZXlfcGF0aBgBIAEoCUoECAIQAyI7Cg5EZWxldGVSZXNwb25zZRIpCgdyZXN1bHRzGAEgAygLMhguc3RhdGVseS5kYi5EZWxldGVSZXN1bHRCZgoOY29tLnN0YXRlbHkuZGJCC0RlbGV0ZVByb3RvUAGiAgNTRFiqAgpTdGF0ZWx5LkRiygIKU3RhdGVseVxEYuICFlN0YXRlbHlcRGJcR1BCTWV0YWRhdGHqAgtTdGF0ZWx5OjpEYmIGcHJvdG8z",
  );

/**
 * Describes the message stately.db.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema = /*@__PURE__*/ messageDesc(file_db_delete, 0);

/**
 * Describes the message stately.db.DeleteItem.
 * Use `create(DeleteItemSchema)` to create a new message.
 */
export const DeleteItemSchema = /*@__PURE__*/ messageDesc(file_db_delete, 1);

/**
 * Describes the message stately.db.DeleteResult.
 * Use `create(DeleteResultSchema)` to create a new message.
 */
export const DeleteResultSchema = /*@__PURE__*/ messageDesc(file_db_delete, 2);

/**
 * Describes the message stately.db.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema = /*@__PURE__*/ messageDesc(file_db_delete, 3);
