// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/delete.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file db/delete.proto.
 */
export const file_db_delete =
  /*@__PURE__*/
  fileDesc(
    "Cg9kYi9kZWxldGUucHJvdG8SCnN0YXRlbHkuZGIiZQoNRGVsZXRlUmVxdWVzdBIQCghzdG9yZV9pZBgBIAEoBBInCgdkZWxldGVzGAMgAygLMhYuc3RhdGVseS5kYi5EZWxldGVJdGVtEhMKC3NjaGVtYV9oYXNoGAUgASgGSgQIBBAFIh4KCkRlbGV0ZUl0ZW0SEAoIa2V5X3BhdGgYASABKAkiJgoMRGVsZXRlUmVzdWx0EhAKCGtleV9wYXRoGAEgASgJSgQIAhADIjsKDkRlbGV0ZVJlc3BvbnNlEikKB3Jlc3VsdHMYASADKAsyGC5zdGF0ZWx5LmRiLkRlbGV0ZVJlc3VsdEJmCg5jb20uc3RhdGVseS5kYkILRGVsZXRlUHJvdG9QAaICA1NEWKoCClN0YXRlbHkuRGLKAgpTdGF0ZWx5XERi4gIWU3RhdGVseVxEYlxHUEJNZXRhZGF0YeoCC1N0YXRlbHk6OkRiYgZwcm90bzM",
  );

/**
 * Describes the message stately.db.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema = /*@__PURE__*/ messageDesc(file_db_delete, 0);

/**
 * Describes the message stately.db.DeleteItem.
 * Use `create(DeleteItemSchema)` to create a new message.
 */
export const DeleteItemSchema = /*@__PURE__*/ messageDesc(file_db_delete, 1);

/**
 * Describes the message stately.db.DeleteResult.
 * Use `create(DeleteResultSchema)` to create a new message.
 */
export const DeleteResultSchema = /*@__PURE__*/ messageDesc(file_db_delete, 2);

/**
 * Describes the message stately.db.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema = /*@__PURE__*/ messageDesc(file_db_delete, 3);
