// @generated by protoc-gen-es v2.2.2 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/item_property.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file db/item_property.proto.
 */
export const file_db_item_property =
  /*@__PURE__*/
  fileDesc(
    "ChZkYi9pdGVtX3Byb3BlcnR5LnByb3RvEgpzdGF0ZWx5LmRiKosCChBTb3J0YWJsZVByb3BlcnR5Eh4KGlNPUlRBQkxFX1BST1BFUlRZX0tFWV9QQVRIEAASKwonU09SVEFCTEVfUFJPUEVSVFlfTEFTVF9NT0RJRklFRF9WRVJTSU9OEAESKQolU09SVEFCTEVfUFJPUEVSVFlfR1JPVVBfTE9DQUxfSU5ERVhfMRAIEikKJVNPUlRBQkxFX1BST1BFUlRZX0dST1VQX0xPQ0FMX0lOREVYXzIQCRIpCiVTT1JUQUJMRV9QUk9QRVJUWV9HUk9VUF9MT0NBTF9JTkRFWF8zEAoSKQolU09SVEFCTEVfUFJPUEVSVFlfR1JPVVBfTE9DQUxfSU5ERVhfNBALQmwKDmNvbS5zdGF0ZWx5LmRiQhFJdGVtUHJvcGVydHlQcm90b1ABogIDU0RYqgIKU3RhdGVseS5EYsoCClN0YXRlbHlcRGLiAhZTdGF0ZWx5XERiXEdQQk1ldGFkYXRh6gILU3RhdGVseTo6RGJiBnByb3RvMw",
  );

/**
 * Describes the enum stately.db.SortableProperty.
 */
export const SortablePropertySchema = /*@__PURE__*/ enumDesc(file_db_item_property, 0);

/**
 * SortableProperty is used to reference a sortable (i.e. locally indexed)
 * property within an item. These properties are either built in, or they must
 * be explicitly declared in the schema / store config so they can be populated
 * when items are written/updated.
 *
 * @generated from enum stately.db.SortableProperty
 */
export const SortableProperty = /*@__PURE__*/ tsEnum(SortablePropertySchema);
