// @generated by protoc-gen-es v2.6.3 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/item.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file db/item.proto.
 */
export const file_db_item =
  /*@__PURE__*/
  fileDesc(
    "Cg1kYi9pdGVtLnByb3RvEgpzdGF0ZWx5LmRiIl4KBEl0ZW0SEQoJaXRlbV90eXBlGAEgASgJEg8KBXByb3RvGAIgASgMSAASJwoEanNvbhgDIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3RIAEIJCgdwYXlsb2FkQmQKDmNvbS5zdGF0ZWx5LmRiQglJdGVtUHJvdG9QAaICA1NEWKoCClN0YXRlbHkuRGLKAgpTdGF0ZWx5XERi4gIWU3RhdGVseVxEYlxHUEJNZXRhZGF0YeoCC1N0YXRlbHk6OkRiYgZwcm90bzM",
    [file_google_protobuf_struct],
  );

/**
 * Describes the message stately.db.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema = /*@__PURE__*/ messageDesc(file_db_item, 0);
