// @generated by protoc-gen-es v2.2.5 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/item_property.proto (package stately.db, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file db/item_property.proto.
 */
export declare const file_db_item_property: GenFile;

/**
 * SortableProperty is used to reference a sortable (i.e. locally indexed)
 * property within an item. These properties are either built in, or they must
 * be explicitly declared in the schema / store config so they can be populated
 * when items are written/updated.
 *
 * @generated from enum stately.db.SortableProperty
 */
export enum SortableProperty {
  /**
   * SORTABLE_PROPERTY_KEY_PATH is the full key path of the item. This is the
   * default sort property if none is specified. TODO: Document how these are ordered.
   *
   * @generated from enum value: SORTABLE_PROPERTY_KEY_PATH = 0;
   */
  KEY_PATH = 0,

  /**
   * SORTABLE_PROPERTY_LAST_MODIFIED_VERSION sorts by the last modified version
   * of the items, with ascending order being from oldest to newest. This is
   * only available if the store / item is configured to track last modified
   * versions.
   *
   * @generated from enum value: SORTABLE_PROPERTY_LAST_MODIFIED_VERSION = 1;
   */
  LAST_MODIFIED_VERSION = 1,

  /**
   * SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_1 through
   * SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_4 are user-specified sortable
   * properties which may be defined in the schema. The maximum supported number
   * of group local indexes currently depends on the store configuration and the
   * underlying database platform.
   *
   * @generated from enum value: SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_1 = 8;
   */
  GROUP_LOCAL_INDEX_1 = 8,

  /**
   * @generated from enum value: SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_2 = 9;
   */
  GROUP_LOCAL_INDEX_2 = 9,

  /**
   * @generated from enum value: SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_3 = 10;
   */
  GROUP_LOCAL_INDEX_3 = 10,

  /**
   * @generated from enum value: SORTABLE_PROPERTY_GROUP_LOCAL_INDEX_4 = 11;
   */
  GROUP_LOCAL_INDEX_4 = 11,
}

/**
 * Describes the enum stately.db.SortableProperty.
 */
export declare const SortablePropertySchema: GenEnum<SortableProperty>;
