// @generated by protoc-gen-es v2.6.1 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/list_token.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file db/list_token.proto.
 */
export const file_db_list_token =
  /*@__PURE__*/
  fileDesc(
    "ChNkYi9saXN0X3Rva2VuLnByb3RvEgpzdGF0ZWx5LmRiImIKCUxpc3RUb2tlbhISCgp0b2tlbl9kYXRhGAEgASgMEhQKDGNhbl9jb250aW51ZRgCIAEoCBIQCghjYW5fc3luYxgDIAEoCBIZChFzY2hlbWFfdmVyc2lvbl9pZBgEIAEoDUJpCg5jb20uc3RhdGVseS5kYkIOTGlzdFRva2VuUHJvdG9QAaICA1NEWKoCClN0YXRlbHkuRGLKAgpTdGF0ZWx5XERi4gIWU3RhdGVseVxEYlxHUEJNZXRhZGF0YeoCC1N0YXRlbHk6OkRiYgZwcm90bzM",
  );

/**
 * Describes the message stately.db.ListToken.
 * Use `create(ListTokenSchema)` to create a new message.
 */
export const ListTokenSchema = /*@__PURE__*/ messageDesc(file_db_list_token, 0);
