// @generated by protoc-gen-es v2.7.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/list.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_db_item } from "./item_pb.js";
import { file_db_list_filters } from "./list_filters_pb.js";
import { file_db_list_token } from "./list_token_pb.js";

/**
 * Describes the file db/list.proto.
 */
export const file_db_list =
  /*@__PURE__*/
  fileDesc(
    "Cg1kYi9saXN0LnByb3RvEgpzdGF0ZWx5LmRiIrICChBCZWdpbkxpc3RSZXF1ZXN0EhAKCHN0b3JlX2lkGAEgASgEEhcKD2tleV9wYXRoX3ByZWZpeBgCIAEoCRINCgVsaW1pdBgDIAEoDRITCgthbGxvd19zdGFsZRgEIAEoCBIxCg5zb3J0X2RpcmVjdGlvbhgGIAEoDjIZLnN0YXRlbHkuZGIuU29ydERpcmVjdGlvbhIZChFzY2hlbWFfdmVyc2lvbl9pZBgHIAEoDRIRCglzY2hlbWFfaWQYCCABKAQSNgoRZmlsdGVyX2NvbmRpdGlvbnMYCSADKAsyGy5zdGF0ZWx5LmRiLkZpbHRlckNvbmRpdGlvbhIwCg5rZXlfY29uZGl0aW9ucxgKIAMoCzIYLnN0YXRlbHkuZGIuS2V5Q29uZGl0aW9uSgQIBRAGInkKDExpc3RSZXNwb25zZRIvCgZyZXN1bHQYASABKAsyHS5zdGF0ZWx5LmRiLkxpc3RQYXJ0aWFsUmVzdWx0SAASLAoIZmluaXNoZWQYAiABKAsyGC5zdGF0ZWx5LmRiLkxpc3RGaW5pc2hlZEgAQgoKCHJlc3BvbnNlIjQKEUxpc3RQYXJ0aWFsUmVzdWx0Eh8KBWl0ZW1zGAEgAygLMhAuc3RhdGVseS5kYi5JdGVtIjQKDExpc3RGaW5pc2hlZBIkCgV0b2tlbhgBIAEoCzIVLnN0YXRlbHkuZGIuTGlzdFRva2VuIkgKDEtleUNvbmRpdGlvbhIQCghrZXlfcGF0aBgBIAEoCRImCghvcGVyYXRvchgCIAEoDjIULnN0YXRlbHkuZGIuT3BlcmF0b3IqOAoNU29ydERpcmVjdGlvbhISCg5TT1JUX0FTQ0VORElORxAAEhMKD1NPUlRfREVTQ0VORElORxABKpwBCghPcGVyYXRvchIYChRPUEVSQVRPUl9VTlNQRUNJRklFRBAAEhkKFU9QRVJBVE9SX0dSRUFURVJfVEhBThAEEiIKHk9QRVJBVE9SX0dSRUFURVJfVEhBTl9PUl9FUVVBTBAFEhYKEk9QRVJBVE9SX0xFU1NfVEhBThAGEh8KG09QRVJBVE9SX0xFU1NfVEhBTl9PUl9FUVVBTBAHQmQKDmNvbS5zdGF0ZWx5LmRiQglMaXN0UHJvdG9QAaICA1NEWKoCClN0YXRlbHkuRGLKAgpTdGF0ZWx5XERi4gIWU3RhdGVseVxEYlxHUEJNZXRhZGF0YeoCC1N0YXRlbHk6OkRiYgZwcm90bzM",
    [file_db_item, file_db_list_filters, file_db_list_token],
  );

/**
 * Describes the message stately.db.BeginListRequest.
 * Use `create(BeginListRequestSchema)` to create a new message.
 */
export const BeginListRequestSchema = /*@__PURE__*/ messageDesc(file_db_list, 0);

/**
 * Describes the message stately.db.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema = /*@__PURE__*/ messageDesc(file_db_list, 1);

/**
 * Describes the message stately.db.ListPartialResult.
 * Use `create(ListPartialResultSchema)` to create a new message.
 */
export const ListPartialResultSchema = /*@__PURE__*/ messageDesc(file_db_list, 2);

/**
 * Describes the message stately.db.ListFinished.
 * Use `create(ListFinishedSchema)` to create a new message.
 */
export const ListFinishedSchema = /*@__PURE__*/ messageDesc(file_db_list, 3);

/**
 * Describes the message stately.db.KeyCondition.
 * Use `create(KeyConditionSchema)` to create a new message.
 */
export const KeyConditionSchema = /*@__PURE__*/ messageDesc(file_db_list, 4);

/**
 * Describes the enum stately.db.SortDirection.
 */
export const SortDirectionSchema = /*@__PURE__*/ enumDesc(file_db_list, 0);

/**
 * SortDirection represents the direction of iteration.
 *
 * @generated from enum stately.db.SortDirection
 */
export const SortDirection = /*@__PURE__*/ tsEnum(SortDirectionSchema);

/**
 * Describes the enum stately.db.Operator.
 */
export const OperatorSchema = /*@__PURE__*/ enumDesc(file_db_list, 1);

/**
 * @generated from enum stately.db.Operator
 */
export const Operator = /*@__PURE__*/ tsEnum(OperatorSchema);
