// @generated by protoc-gen-es v2.5.2 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/list_filters.proto (package stately.db, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file db/list_filters.proto.
 */
export declare const file_db_list_filters: GenFile;

/**
 * @generated from message stately.db.FilterCondition
 */
export declare type FilterCondition = Message<"stately.db.FilterCondition"> & {
  /**
   * @generated from oneof stately.db.FilterCondition.value
   */
  value:
    | {
        /**
         * item_type is the type of item to filter by.
         *
         * @generated from field: string item_type = 1;
         */
        value: string;
        case: "itemType";
      }
    | { case: undefined; value?: undefined };
};

/**
 * Describes the message stately.db.FilterCondition.
 * Use `create(FilterConditionSchema)` to create a new message.
 */
export declare const FilterConditionSchema: GenMessage<FilterCondition>;
