// @generated by protoc-gen-es v2.5.2 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/list_filters.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file db/list_filters.proto.
 */
export const file_db_list_filters =
  /*@__PURE__*/
  fileDesc(
    "ChVkYi9saXN0X2ZpbHRlcnMucHJvdG8SCnN0YXRlbHkuZGIiLwoPRmlsdGVyQ29uZGl0aW9uEhMKCWl0ZW1fdHlwZRgBIAEoCUgAQgcKBXZhbHVlQmsKDmNvbS5zdGF0ZWx5LmRiQhBMaXN0RmlsdGVyc1Byb3RvUAGiAgNTRFiqAgpTdGF0ZWx5LkRiygIKU3RhdGVseVxEYuICFlN0YXRlbHlcRGJcR1BCTWV0YWRhdGHqAgtTdGF0ZWx5OjpEYmIGcHJvdG8z",
  );

/**
 * Describes the message stately.db.FilterCondition.
 * Use `create(FilterConditionSchema)` to create a new message.
 */
export const FilterConditionSchema = /*@__PURE__*/ messageDesc(file_db_list_filters, 0);
