// @generated by protoc-gen-es v2.6.1 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/list.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_db_item } from "./item_pb.js";
import { file_db_item_property } from "./item_property_pb.js";
import { file_db_list_filters } from "./list_filters_pb.js";
import { file_db_list_token } from "./list_token_pb.js";

/**
 * Describes the file db/list.proto.
 */
export const file_db_list =
  /*@__PURE__*/
  fileDesc(
    "Cg1kYi9saXN0LnByb3RvEgpzdGF0ZWx5LmRiIuECChBCZWdpbkxpc3RSZXF1ZXN0EhAKCHN0b3JlX2lkGAEgASgEEhcKD2tleV9wYXRoX3ByZWZpeBgCIAEoCRINCgVsaW1pdBgDIAEoDRITCgthbGxvd19zdGFsZRgEIAEoCBIzCg1zb3J0X3Byb3BlcnR5GAUgASgOMhwuc3RhdGVseS5kYi5Tb3J0YWJsZVByb3BlcnR5EjEKDnNvcnRfZGlyZWN0aW9uGAYgASgOMhkuc3RhdGVseS5kYi5Tb3J0RGlyZWN0aW9uEhkKEXNjaGVtYV92ZXJzaW9uX2lkGAcgASgNEhEKCXNjaGVtYV9pZBgIIAEoBBI2ChFmaWx0ZXJfY29uZGl0aW9ucxgJIAMoCzIbLnN0YXRlbHkuZGIuRmlsdGVyQ29uZGl0aW9uEjAKDmtleV9jb25kaXRpb25zGAogAygLMhguc3RhdGVseS5kYi5LZXlDb25kaXRpb24ieQoMTGlzdFJlc3BvbnNlEi8KBnJlc3VsdBgBIAEoCzIdLnN0YXRlbHkuZGIuTGlzdFBhcnRpYWxSZXN1bHRIABIsCghmaW5pc2hlZBgCIAEoCzIYLnN0YXRlbHkuZGIuTGlzdEZpbmlzaGVkSABCCgoIcmVzcG9uc2UiNAoRTGlzdFBhcnRpYWxSZXN1bHQSHwoFaXRlbXMYASADKAsyEC5zdGF0ZWx5LmRiLkl0ZW0iNAoMTGlzdEZpbmlzaGVkEiQKBXRva2VuGAEgASgLMhUuc3RhdGVseS5kYi5MaXN0VG9rZW4iSAoMS2V5Q29uZGl0aW9uEhAKCGtleV9wYXRoGAEgASgJEiYKCG9wZXJhdG9yGAIgASgOMhQuc3RhdGVseS5kYi5PcGVyYXRvcio4Cg1Tb3J0RGlyZWN0aW9uEhIKDlNPUlRfQVNDRU5ESU5HEAASEwoPU09SVF9ERVNDRU5ESU5HEAEqnAEKCE9wZXJhdG9yEhgKFE9QRVJBVE9SX1VOU1BFQ0lGSUVEEAASGQoVT1BFUkFUT1JfR1JFQVRFUl9USEFOEAQSIgoeT1BFUkFUT1JfR1JFQVRFUl9USEFOX09SX0VRVUFMEAUSFgoST1BFUkFUT1JfTEVTU19USEFOEAYSHwobT1BFUkFUT1JfTEVTU19USEFOX09SX0VRVUFMEAdCZAoOY29tLnN0YXRlbHkuZGJCCUxpc3RQcm90b1ABogIDU0RYqgIKU3RhdGVseS5EYsoCClN0YXRlbHlcRGLiAhZTdGF0ZWx5XERiXEdQQk1ldGFkYXRh6gILU3RhdGVseTo6RGJiBnByb3RvMw",
    [file_db_item, file_db_item_property, file_db_list_filters, file_db_list_token],
  );

/**
 * Describes the message stately.db.BeginListRequest.
 * Use `create(BeginListRequestSchema)` to create a new message.
 */
export const BeginListRequestSchema = /*@__PURE__*/ messageDesc(file_db_list, 0);

/**
 * Describes the message stately.db.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema = /*@__PURE__*/ messageDesc(file_db_list, 1);

/**
 * Describes the message stately.db.ListPartialResult.
 * Use `create(ListPartialResultSchema)` to create a new message.
 */
export const ListPartialResultSchema = /*@__PURE__*/ messageDesc(file_db_list, 2);

/**
 * Describes the message stately.db.ListFinished.
 * Use `create(ListFinishedSchema)` to create a new message.
 */
export const ListFinishedSchema = /*@__PURE__*/ messageDesc(file_db_list, 3);

/**
 * Describes the message stately.db.KeyCondition.
 * Use `create(KeyConditionSchema)` to create a new message.
 */
export const KeyConditionSchema = /*@__PURE__*/ messageDesc(file_db_list, 4);

/**
 * Describes the enum stately.db.SortDirection.
 */
export const SortDirectionSchema = /*@__PURE__*/ enumDesc(file_db_list, 0);

/**
 * SortDirection represents the direction of iteration.
 *
 * @generated from enum stately.db.SortDirection
 */
export const SortDirection = /*@__PURE__*/ tsEnum(SortDirectionSchema);

/**
 * Describes the enum stately.db.Operator.
 */
export const OperatorSchema = /*@__PURE__*/ enumDesc(file_db_list, 1);

/**
 * @generated from enum stately.db.Operator
 */
export const Operator = /*@__PURE__*/ tsEnum(OperatorSchema);
