// @generated by protoc-gen-es v2.2.3 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/list.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_db_item } from "./item_pb.js";
import { file_db_item_property } from "./item_property_pb.js";
import { file_db_list_token } from "./list_token_pb.js";

/**
 * Describes the file db/list.proto.
 */
export const file_db_list =
  /*@__PURE__*/
  fileDesc(
    "Cg1kYi9saXN0LnByb3RvEgpzdGF0ZWx5LmRiIuQBChBCZWdpbkxpc3RSZXF1ZXN0EhAKCHN0b3JlX2lkGAEgASgEEhcKD2tleV9wYXRoX3ByZWZpeBgCIAEoCRINCgVsaW1pdBgDIAEoDRITCgthbGxvd19zdGFsZRgEIAEoCBIzCg1zb3J0X3Byb3BlcnR5GAUgASgOMhwuc3RhdGVseS5kYi5Tb3J0YWJsZVByb3BlcnR5EjEKDnNvcnRfZGlyZWN0aW9uGAYgASgOMhkuc3RhdGVseS5kYi5Tb3J0RGlyZWN0aW9uEhkKEXNjaGVtYV92ZXJzaW9uX2lkGAcgASgNInkKDExpc3RSZXNwb25zZRIvCgZyZXN1bHQYASABKAsyHS5zdGF0ZWx5LmRiLkxpc3RQYXJ0aWFsUmVzdWx0SAASLAoIZmluaXNoZWQYAiABKAsyGC5zdGF0ZWx5LmRiLkxpc3RGaW5pc2hlZEgAQgoKCHJlc3BvbnNlIjQKEUxpc3RQYXJ0aWFsUmVzdWx0Eh8KBWl0ZW1zGAEgAygLMhAuc3RhdGVseS5kYi5JdGVtIjQKDExpc3RGaW5pc2hlZBIkCgV0b2tlbhgBIAEoCzIVLnN0YXRlbHkuZGIuTGlzdFRva2VuKjgKDVNvcnREaXJlY3Rpb24SEgoOU09SVF9BU0NFTkRJTkcQABITCg9TT1JUX0RFU0NFTkRJTkcQAUJkCg5jb20uc3RhdGVseS5kYkIJTGlzdFByb3RvUAGiAgNTRFiqAgpTdGF0ZWx5LkRiygIKU3RhdGVseVxEYuICFlN0YXRlbHlcRGJcR1BCTWV0YWRhdGHqAgtTdGF0ZWx5OjpEYmIGcHJvdG8z",
    [file_db_item, file_db_item_property, file_db_list_token],
  );

/**
 * Describes the message stately.db.BeginListRequest.
 * Use `create(BeginListRequestSchema)` to create a new message.
 */
export const BeginListRequestSchema = /*@__PURE__*/ messageDesc(file_db_list, 0);

/**
 * Describes the message stately.db.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema = /*@__PURE__*/ messageDesc(file_db_list, 1);

/**
 * Describes the message stately.db.ListPartialResult.
 * Use `create(ListPartialResultSchema)` to create a new message.
 */
export const ListPartialResultSchema = /*@__PURE__*/ messageDesc(file_db_list, 2);

/**
 * Describes the message stately.db.ListFinished.
 * Use `create(ListFinishedSchema)` to create a new message.
 */
export const ListFinishedSchema = /*@__PURE__*/ messageDesc(file_db_list, 3);

/**
 * Describes the enum stately.db.SortDirection.
 */
export const SortDirectionSchema = /*@__PURE__*/ enumDesc(file_db_list, 0);

/**
 * SortDirection represents the direction of iteration.
 *
 * @generated from enum stately.db.SortDirection
 */
export const SortDirection = /*@__PURE__*/ tsEnum(SortDirectionSchema);
