// @generated by protoc-gen-es v2.6.1 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/list_filters.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file db/list_filters.proto.
 */
export const file_db_list_filters =
  /*@__PURE__*/
  fileDesc(
    "ChVkYi9saXN0X2ZpbHRlcnMucHJvdG8SCnN0YXRlbHkuZGIiZAoPRmlsdGVyQ29uZGl0aW9uEhMKCWl0ZW1fdHlwZRgBIAEoCUgAEjMKDmNlbF9leHByZXNzaW9uGAIgASgLMhkuc3RhdGVseS5kYi5DZWxFeHByZXNzaW9uSABCBwoFdmFsdWUiNgoNQ2VsRXhwcmVzc2lvbhIRCglpdGVtX3R5cGUYASABKAkSEgoKZXhwcmVzc2lvbhgCIAEoCUJrCg5jb20uc3RhdGVseS5kYkIQTGlzdEZpbHRlcnNQcm90b1ABogIDU0RYqgIKU3RhdGVseS5EYsoCClN0YXRlbHlcRGLiAhZTdGF0ZWx5XERiXEdQQk1ldGFkYXRh6gILU3RhdGVseTo6RGJiBnByb3RvMw",
  );

/**
 * Describes the message stately.db.FilterCondition.
 * Use `create(FilterConditionSchema)` to create a new message.
 */
export const FilterConditionSchema = /*@__PURE__*/ messageDesc(file_db_list_filters, 0);

/**
 * Describes the message stately.db.CelExpression.
 * Use `create(CelExpressionSchema)` to create a new message.
 */
export const CelExpressionSchema = /*@__PURE__*/ messageDesc(file_db_list_filters, 1);
