// @generated by protoc-gen-es v2.6.1 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/put.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_db_item } from "./item_pb.js";

/**
 * Describes the file db/put.proto.
 */
export const file_db_put =
  /*@__PURE__*/
  fileDesc(
    "CgxkYi9wdXQucHJvdG8SCnN0YXRlbHkuZGIibwoKUHV0UmVxdWVzdBIQCghzdG9yZV9pZBgBIAEoBBIhCgRwdXRzGAIgAygLMhMuc3RhdGVseS5kYi5QdXRJdGVtEhkKEXNjaGVtYV92ZXJzaW9uX2lkGAMgASgNEhEKCXNjaGVtYV9pZBgEIAEoBCJoCgdQdXRJdGVtEh4KBGl0ZW0YASABKAsyEC5zdGF0ZWx5LmRiLkl0ZW0SJQodb3ZlcndyaXRlX21ldGFkYXRhX3RpbWVzdGFtcHMYAiABKAgSFgoObXVzdF9ub3RfZXhpc3QYAyABKAgiLgoLUHV0UmVzcG9uc2USHwoFaXRlbXMYASADKAsyEC5zdGF0ZWx5LmRiLkl0ZW1CYwoOY29tLnN0YXRlbHkuZGJCCFB1dFByb3RvUAGiAgNTRFiqAgpTdGF0ZWx5LkRiygIKU3RhdGVseVxEYuICFlN0YXRlbHlcRGJcR1BCTWV0YWRhdGHqAgtTdGF0ZWx5OjpEYmIGcHJvdG8z",
    [file_db_item],
  );

/**
 * Describes the message stately.db.PutRequest.
 * Use `create(PutRequestSchema)` to create a new message.
 */
export const PutRequestSchema = /*@__PURE__*/ messageDesc(file_db_put, 0);

/**
 * Describes the message stately.db.PutItem.
 * Use `create(PutItemSchema)` to create a new message.
 */
export const PutItemSchema = /*@__PURE__*/ messageDesc(file_db_put, 1);

/**
 * Describes the message stately.db.PutResponse.
 * Use `create(PutResponseSchema)` to create a new message.
 */
export const PutResponseSchema = /*@__PURE__*/ messageDesc(file_db_put, 2);
