// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/put.proto (package stately.db, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Item } from "./item_pb.js";

/**
 * Describes the file db/put.proto.
 */
export declare const file_db_put: GenFile;

/**
 * @generated from message stately.db.PutRequest
 */
export declare type PutRequest = Message<"stately.db.PutRequest"> & {
  /**
   * store_id is a globally unique Store ID, which can be looked up from the
   * console or CLI.
   *
   * @generated from field: uint64 store_id = 1;
   */
  storeId: bigint;

  /**
   * puts is one or more items to be put into the Store.
   *
   * @generated from field: repeated stately.db.PutItem puts = 2;
   */
  puts: PutItem[];
};

/**
 * Describes the message stately.db.PutRequest.
 * Use `create(PutRequestSchema)` to create a new message.
 */
export declare const PutRequestSchema: GenMessage<PutRequest>;

/**
 * @generated from message stately.db.PutItem
 */
export declare type PutItem = Message<"stately.db.PutItem"> & {
  /**
   * item is the data to be put, including its item_type.
   *
   * @generated from field: stately.db.Item item = 1;
   */
  item?: Item;
};

/**
 * Describes the message stately.db.PutItem.
 * Use `create(PutItemSchema)` to create a new message.
 */
export declare const PutItemSchema: GenMessage<PutItem>;

/**
 * @generated from message stately.db.PutResponse
 */
export declare type PutResponse = Message<"stately.db.PutResponse"> & {
  /**
   * items is the full result of each put operation. The response items are in
   * the same order as the request items. Each item is fully "filled out" - for
   * example, `initialValue` and `fromMetadata` fields are resolved.
   *
   * @generated from field: repeated stately.db.Item items = 1;
   */
  items: Item[];
};

/**
 * Describes the message stately.db.PutResponse.
 * Use `create(PutResponseSchema)` to create a new message.
 */
export declare const PutResponseSchema: GenMessage<PutResponse>;
