// @generated by protoc-gen-es v2.3.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/scan.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file db/scan.proto.
 */
export const file_db_scan =
  /*@__PURE__*/
  fileDesc(
    "Cg1kYi9zY2FuLnByb3RvEgpzdGF0ZWx5LmRiIi8KD0ZpbHRlckNvbmRpdGlvbhITCglpdGVtX3R5cGUYASABKAlIAEIHCgV2YWx1ZSLVAQoQQmVnaW5TY2FuUmVxdWVzdBIQCghzdG9yZV9pZBgBIAEoBBI1ChBmaWx0ZXJfY29uZGl0aW9uGAIgAygLMhsuc3RhdGVseS5kYi5GaWx0ZXJDb25kaXRpb24SDQoFbGltaXQYAyABKA0SOwoTc2VnbWVudGF0aW9uX3BhcmFtcxgEIAEoCzIeLnN0YXRlbHkuZGIuU2VnbWVudGF0aW9uUGFyYW1zEhkKEXNjaGVtYV92ZXJzaW9uX2lkGAUgASgNEhEKCXNjaGVtYV9pZBgGIAEoBCJDChJTZWdtZW50YXRpb25QYXJhbXMSFgoOdG90YWxfc2VnbWVudHMYBSABKA0SFQoNc2VnbWVudF9pbmRleBgGIAEoDUJkCg5jb20uc3RhdGVseS5kYkIJU2NhblByb3RvUAGiAgNTRFiqAgpTdGF0ZWx5LkRiygIKU3RhdGVseVxEYuICFlN0YXRlbHlcRGJcR1BCTWV0YWRhdGHqAgtTdGF0ZWx5OjpEYmIGcHJvdG8z",
  );

/**
 * Describes the message stately.db.FilterCondition.
 * Use `create(FilterConditionSchema)` to create a new message.
 */
export const FilterConditionSchema = /*@__PURE__*/ messageDesc(file_db_scan, 0);

/**
 * Describes the message stately.db.BeginScanRequest.
 * Use `create(BeginScanRequestSchema)` to create a new message.
 */
export const BeginScanRequestSchema = /*@__PURE__*/ messageDesc(file_db_scan, 1);

/**
 * Describes the message stately.db.SegmentationParams.
 * Use `create(SegmentationParamsSchema)` to create a new message.
 */
export const SegmentationParamsSchema = /*@__PURE__*/ messageDesc(file_db_scan, 2);
