// @generated by protoc-gen-es v2.1.0 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/scan_root_paths.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file db/scan_root_paths.proto.
 */
export const file_db_scan_root_paths =
  /*@__PURE__*/
  fileDesc(
    "ChhkYi9zY2FuX3Jvb3RfcGF0aHMucHJvdG8SCnN0YXRlbHkuZGIibAoUU2NhblJvb3RQYXRoc1JlcXVlc3QSEAoIc3RvcmVfaWQYASABKAQSDQoFbGltaXQYAiABKA0SGAoQcGFnaW5hdGlvbl90b2tlbhgDIAEoDBIZChFzY2hlbWFfdmVyc2lvbl9pZBgEIAEoDSJiChVTY2FuUm9vdFBhdGhzUmVzcG9uc2USLwoHcmVzdWx0cxgBIAMoCzIeLnN0YXRlbHkuZGIuU2NhblJvb3RQYXRoUmVzdWx0EhgKEHBhZ2luYXRpb25fdG9rZW4YAiABKAwiJgoSU2NhblJvb3RQYXRoUmVzdWx0EhAKCGtleV9wYXRoGAEgASgJQm0KDmNvbS5zdGF0ZWx5LmRiQhJTY2FuUm9vdFBhdGhzUHJvdG9QAaICA1NEWKoCClN0YXRlbHkuRGLKAgpTdGF0ZWx5XERi4gIWU3RhdGVseVxEYlxHUEJNZXRhZGF0YeoCC1N0YXRlbHk6OkRiYgZwcm90bzM",
  );

/**
 * Describes the message stately.db.ScanRootPathsRequest.
 * Use `create(ScanRootPathsRequestSchema)` to create a new message.
 */
export const ScanRootPathsRequestSchema = /*@__PURE__*/ messageDesc(file_db_scan_root_paths, 0);

/**
 * Describes the message stately.db.ScanRootPathsResponse.
 * Use `create(ScanRootPathsResponseSchema)` to create a new message.
 */
export const ScanRootPathsResponseSchema = /*@__PURE__*/ messageDesc(file_db_scan_root_paths, 1);

/**
 * Describes the message stately.db.ScanRootPathResult.
 * Use `create(ScanRootPathResultSchema)` to create a new message.
 */
export const ScanRootPathResultSchema = /*@__PURE__*/ messageDesc(file_db_scan_root_paths, 2);
