// @generated by protoc-gen-es v2.6.3 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/scan.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_db_list_filters } from "./list_filters_pb.js";

/**
 * Describes the file db/scan.proto.
 */
export const file_db_scan =
  /*@__PURE__*/
  fileDesc(
    "Cg1kYi9zY2FuLnByb3RvEgpzdGF0ZWx5LmRiItYBChBCZWdpblNjYW5SZXF1ZXN0EhAKCHN0b3JlX2lkGAEgASgEEjYKEWZpbHRlcl9jb25kaXRpb25zGAIgAygLMhsuc3RhdGVseS5kYi5GaWx0ZXJDb25kaXRpb24SDQoFbGltaXQYAyABKA0SOwoTc2VnbWVudGF0aW9uX3BhcmFtcxgEIAEoCzIeLnN0YXRlbHkuZGIuU2VnbWVudGF0aW9uUGFyYW1zEhkKEXNjaGVtYV92ZXJzaW9uX2lkGAUgASgNEhEKCXNjaGVtYV9pZBgGIAEoBCJDChJTZWdtZW50YXRpb25QYXJhbXMSFgoOdG90YWxfc2VnbWVudHMYBSABKA0SFQoNc2VnbWVudF9pbmRleBgGIAEoDUJkCg5jb20uc3RhdGVseS5kYkIJU2NhblByb3RvUAGiAgNTRFiqAgpTdGF0ZWx5LkRiygIKU3RhdGVseVxEYuICFlN0YXRlbHlcRGJcR1BCTWV0YWRhdGHqAgtTdGF0ZWx5OjpEYmIGcHJvdG8z",
    [file_db_list_filters],
  );

/**
 * Describes the message stately.db.BeginScanRequest.
 * Use `create(BeginScanRequestSchema)` to create a new message.
 */
export const BeginScanRequestSchema = /*@__PURE__*/ messageDesc(file_db_scan, 0);

/**
 * Describes the message stately.db.SegmentationParams.
 * Use `create(SegmentationParamsSchema)` to create a new message.
 */
export const SegmentationParamsSchema = /*@__PURE__*/ messageDesc(file_db_scan, 1);
