// @generated by protoc-gen-es v2.5.2 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/scan.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_db_list_filters } from "./list_filters_pb.js";

/**
 * Describes the file db/scan.proto.
 */
export const file_db_scan =
  /*@__PURE__*/
  fileDesc(
    "Cg1kYi9zY2FuLnByb3RvEgpzdGF0ZWx5LmRiItUBChBCZWdpblNjYW5SZXF1ZXN0EhAKCHN0b3JlX2lkGAEgASgEEjUKEGZpbHRlcl9jb25kaXRpb24YAiADKAsyGy5zdGF0ZWx5LmRiLkZpbHRlckNvbmRpdGlvbhINCgVsaW1pdBgDIAEoDRI7ChNzZWdtZW50YXRpb25fcGFyYW1zGAQgASgLMh4uc3RhdGVseS5kYi5TZWdtZW50YXRpb25QYXJhbXMSGQoRc2NoZW1hX3ZlcnNpb25faWQYBSABKA0SEQoJc2NoZW1hX2lkGAYgASgEIkMKElNlZ21lbnRhdGlvblBhcmFtcxIWCg50b3RhbF9zZWdtZW50cxgFIAEoDRIVCg1zZWdtZW50X2luZGV4GAYgASgNQmQKDmNvbS5zdGF0ZWx5LmRiQglTY2FuUHJvdG9QAaICA1NEWKoCClN0YXRlbHkuRGLKAgpTdGF0ZWx5XERi4gIWU3RhdGVseVxEYlxHUEJNZXRhZGF0YeoCC1N0YXRlbHk6OkRiYgZwcm90bzM",
    [file_db_list_filters],
  );

/**
 * Describes the message stately.db.BeginScanRequest.
 * Use `create(BeginScanRequestSchema)` to create a new message.
 */
export const BeginScanRequestSchema = /*@__PURE__*/ messageDesc(file_db_scan, 0);

/**
 * Describes the message stately.db.SegmentationParams.
 * Use `create(SegmentationParamsSchema)` to create a new message.
 */
export const SegmentationParamsSchema = /*@__PURE__*/ messageDesc(file_db_scan, 1);
