// @generated by protoc-gen-es v2.2.4 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/scan_root_paths.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file db/scan_root_paths.proto.
 */
export const file_db_scan_root_paths =
  /*@__PURE__*/
  fileDesc(
    "ChhkYi9zY2FuX3Jvb3RfcGF0aHMucHJvdG8SCnN0YXRlbHkuZGIifwoUU2NhblJvb3RQYXRoc1JlcXVlc3QSEAoIc3RvcmVfaWQYASABKAQSDQoFbGltaXQYAiABKA0SGAoQcGFnaW5hdGlvbl90b2tlbhgDIAEoDBIZChFzY2hlbWFfdmVyc2lvbl9pZBgEIAEoDRIRCglzY2hlbWFfaWQYBSABKAQiYgoVU2NhblJvb3RQYXRoc1Jlc3BvbnNlEi8KB3Jlc3VsdHMYASADKAsyHi5zdGF0ZWx5LmRiLlNjYW5Sb290UGF0aFJlc3VsdBIYChBwYWdpbmF0aW9uX3Rva2VuGAIgASgMIiYKElNjYW5Sb290UGF0aFJlc3VsdBIQCghrZXlfcGF0aBgBIAEoCUJtCg5jb20uc3RhdGVseS5kYkISU2NhblJvb3RQYXRoc1Byb3RvUAGiAgNTRFiqAgpTdGF0ZWx5LkRiygIKU3RhdGVseVxEYuICFlN0YXRlbHlcRGJcR1BCTWV0YWRhdGHqAgtTdGF0ZWx5OjpEYmIGcHJvdG8z",
  );

/**
 * Describes the message stately.db.ScanRootPathsRequest.
 * Use `create(ScanRootPathsRequestSchema)` to create a new message.
 */
export const ScanRootPathsRequestSchema = /*@__PURE__*/ messageDesc(file_db_scan_root_paths, 0);

/**
 * Describes the message stately.db.ScanRootPathsResponse.
 * Use `create(ScanRootPathsResponseSchema)` to create a new message.
 */
export const ScanRootPathsResponseSchema = /*@__PURE__*/ messageDesc(file_db_scan_root_paths, 1);

/**
 * Describes the message stately.db.ScanRootPathResult.
 * Use `create(ScanRootPathResultSchema)` to create a new message.
 */
export const ScanRootPathResultSchema = /*@__PURE__*/ messageDesc(file_db_scan_root_paths, 2);
