// @generated by protoc-gen-es v2.5.2 with parameter "target=js+dts,import_extension=.js"
// @generated from file db/sync_list.proto (package stately.db, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_db_item } from "./item_pb.js";
import { file_db_list } from "./list_pb.js";

/**
 * Describes the file db/sync_list.proto.
 */
export const file_db_sync_list =
  /*@__PURE__*/
  fileDesc(
    "ChJkYi9zeW5jX2xpc3QucHJvdG8SCnN0YXRlbHkuZGIiUwoPU3luY0xpc3RSZXF1ZXN0EhIKCnRva2VuX2RhdGEYASABKAwSGQoRc2NoZW1hX3ZlcnNpb25faWQYBSABKA0SEQoJc2NoZW1hX2lkGAYgASgEIq8BChBTeW5jTGlzdFJlc3BvbnNlEioKBXJlc2V0GAEgASgLMhkuc3RhdGVseS5kYi5TeW5jTGlzdFJlc2V0SAASNQoGcmVzdWx0GAIgASgLMiMuc3RhdGVseS5kYi5TeW5jTGlzdFBhcnRpYWxSZXNwb25zZUgAEiwKCGZpbmlzaGVkGAMgASgLMhguc3RhdGVseS5kYi5MaXN0RmluaXNoZWRIAEIKCghyZXNwb25zZSIPCg1TeW5jTGlzdFJlc2V0IqEBChdTeW5jTGlzdFBhcnRpYWxSZXNwb25zZRInCg1jaGFuZ2VkX2l0ZW1zGAEgAygLMhAuc3RhdGVseS5kYi5JdGVtEi4KDWRlbGV0ZWRfaXRlbXMYAiADKAsyFy5zdGF0ZWx5LmRiLkRlbGV0ZWRJdGVtEi0KJXVwZGF0ZWRfaXRlbV9rZXlzX291dHNpZGVfbGlzdF93aW5kb3cYAyADKAkiHwoLRGVsZXRlZEl0ZW0SEAoIa2V5X3BhdGgYASABKAlCaAoOY29tLnN0YXRlbHkuZGJCDVN5bmNMaXN0UHJvdG9QAaICA1NEWKoCClN0YXRlbHkuRGLKAgpTdGF0ZWx5XERi4gIWU3RhdGVseVxEYlxHUEJNZXRhZGF0YeoCC1N0YXRlbHk6OkRiYgZwcm90bzM",
    [file_db_item, file_db_list],
  );

/**
 * Describes the message stately.db.SyncListRequest.
 * Use `create(SyncListRequestSchema)` to create a new message.
 */
export const SyncListRequestSchema = /*@__PURE__*/ messageDesc(file_db_sync_list, 0);

/**
 * Describes the message stately.db.SyncListResponse.
 * Use `create(SyncListResponseSchema)` to create a new message.
 */
export const SyncListResponseSchema = /*@__PURE__*/ messageDesc(file_db_sync_list, 1);

/**
 * Describes the message stately.db.SyncListReset.
 * Use `create(SyncListResetSchema)` to create a new message.
 */
export const SyncListResetSchema = /*@__PURE__*/ messageDesc(file_db_sync_list, 2);

/**
 * Describes the message stately.db.SyncListPartialResponse.
 * Use `create(SyncListPartialResponseSchema)` to create a new message.
 */
export const SyncListPartialResponseSchema = /*@__PURE__*/ messageDesc(file_db_sync_list, 3);

/**
 * Describes the message stately.db.DeletedItem.
 * Use `create(DeletedItemSchema)` to create a new message.
 */
export const DeletedItemSchema = /*@__PURE__*/ messageDesc(file_db_sync_list, 4);
