/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal.js";

/** Nothing here - the auth token contains the user ID. */
export interface GetCallerIdentityRequest {}

export interface GetCallerIdentityResponse {
  /**
   * user_id is the user's ID in Stately. This is generated by us during enrollment
   * and can may also be referred to as member ID within Stately.
   */
  userId: bigint;
}

function createBaseGetCallerIdentityRequest(): GetCallerIdentityRequest {
  return {};
}

export const GetCallerIdentityRequest = {
  encode(_: GetCallerIdentityRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetCallerIdentityRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCallerIdentityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

function createBaseGetCallerIdentityResponse(): GetCallerIdentityResponse {
  return { userId: BigInt("0") };
}

export const GetCallerIdentityResponse = {
  encode(message: GetCallerIdentityResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.userId !== BigInt("0")) {
      if (BigInt.asUintN(64, message.userId) !== message.userId) {
        throw new globalThis.Error(
          "value provided for field message.userId of type uint64 too large",
        );
      }
      writer.uint32(8).uint64(message.userId.toString());
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetCallerIdentityResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCallerIdentityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.userId = longToBigint(reader.uint64() as Long);
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },
};

function longToBigint(long: Long) {
  return BigInt(long.toString());
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
