// @generated by errgen.go. DO NOT EDIT.

/**
 * An enum containing the complete list of Stately error codes
 * @readonly
 * @enum {string}
 */
export const enum ErrorCode {
  /**
   * This error indicates that an unknown error occurred.
   */
  Unknown = "Unknown",

  /**
   * This error indicates that the attempted filesystem operation was invalid.
   * Please try again with a different path.
   */
  FilesystemInvalid = "FilesystemInvalid",

  /**
   * This error indicates that an invalid argument was provided. Please check
   * the arguments and try again.
   */
  InvalidArgument = "InvalidArgument",

  /**
   * This error indicates that the key ID provided is invalid. Please provide a
   * valid key ID.
   */
  InvalidKeyId = "InvalidKeyId",

  /**
   * This error indicates that the signature used to verify the data is
   * invalid. Please retry the operation.
   */
  InvalidSignature = "InvalidSignature",

  /**
   * This error indicates that the item type that was returned from a getor put
   * API did not match the item type requested by the user. Please ensure the
   * item type is correct and try again.
   */
  ItemTypeMismatch = "ItemTypeMismatch",

  /**
   * This error indicates that Stately failed to marshal the provided data.
   * Please ensure your data is valid and try again.
   */
  MarshalFailure = "MarshalFailure",

  /**
   * This error indicates that the argument provided to a put API was not an
   * item type. Make sure to create items with `client.newItem`.
   */
  NotAnItem = "NotAnItem",

  /**
   * This error indicates that the token used to authenticate the request has
   * expired. Please refresh the token and try again.
   */
  TokenExpired = "TokenExpired",

  /**
   * This error indicates that the item type returned by an API, or provided as
   * an argument, is not one of the types in the generated schema. This
   * probably means your schema is out of date.
   */
  UnknownItemType = "UnknownItemType",

  /**
   * This error indicates that Stately failed to unmarshal the provided data.
   * Please ensure your data is valid and try again.
   */
  UnmarshalFailure = "UnmarshalFailure",

  /**
   * This error indicates alias operation which would result in unsafe state.
   * Please select a different alias.
   */
  UnsafeAliasOperation = "UnsafeAliasOperation",

  /**
   * This error indicates that the operation failed because the file or
   * directory does not exist. Please create the directory or file first or
   * specify a path that exists.
   */
  FilesystemNotExists = "FilesystemNotExists",

  /**
   * This error indicates that the client or server tried to access an
   * organization that does not exist, or access to this organization is not
   * allowed. If you are sure that this organization exists and that you should
   * have access, please contact support.
   */
  OrganizationNotFound = "OrganizationNotFound",

  /**
   * This error indicates that the client or server tried to access a project
   * that does not exist, or access to this project is not allowed. If you are
   * sure that this project exists and that you should have access, please
   * contact support.
   */
  ProjectNotFound = "ProjectNotFound",

  /**
   * This error indicates that the client or server tried to access a store
   * that does not exist, or access to this store is not allowed. If you are
   * sure that this store exists and that you should have access, please
   * contact support.
   */
  StoreNotFound = "StoreNotFound",

  /**
   * This error indicates that the client or server tried to access a user that
   * does not exist, or access to this user is not allowed. If you are sure
   * that this user exists and that you should have access, please contact
   * support.
   */
  UserNotFound = "UserNotFound",

  /**
   * This error indicates that the logged in user does not have an associated
   * user in the Stately backend. This can often be fixed by simply logging
   * into https://console.stately.cloud to trigger a refresh. If that fails,
   * please contact support.
   */
  UserNotRegistered = "UserNotRegistered",

  /**
   * This error indicates that creating file or directory failed because the
   * file or directory already exists. Please specify a different path or clear
   * the existing file or directory.
   */
  FilesystemAlreadyExists = "FilesystemAlreadyExists",

  /**
   * This error indicates that the filesystem operation is not allowed. Please
   * change the filesystem permissions or specify a different path.
   */
  FilesystemPermissionDenied = "FilesystemPermissionDenied",

  /**
   * This error indicates that operation failed because the file closed
   * unexpectedly. Please retry.
   */
  FilesystemClosed = "FilesystemClosed",

  /**
   * This error indicates that the client or server tried to use a stream that
   * was already closed. Please retry.
   */
  StreamClosed = "StreamClosed",

  /**
   * This error indicates that the operation failed due to an append collision
   * on the Stately backend. Please retry.
   */
  AppendCollision = "AppendCollision",

  /**
   * This error indicates that the operation failed due to a concurrent
   * modification. Please retry.
   */
  ConcurrentModification = "ConcurrentModification",

  /**
   * This error indicates that the operation failed due to failed conditional
   * check. Please retry.
   */
  ConditionalCheckFailed = "ConditionalCheckFailed",

  /**
   * This error indicates a bug in StatelyDB. Please contact support.
   */
  Internal = "Internal",

  /**
   * This error indicates that the operation failed due to an invalid token on
   * the Stately backend. Please contact support.
   */
  InvalidToken = "InvalidToken",
}
